version: '3.8'

services:
  app1:
    build: ./backend
    environment:
      - APP_NAME=App1
    # semua backend menulis ke shared_logs yang dimount di /var/log/nginx
    volumes:
      - shared_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  app2:
    build: ./backend
    environment:
      - APP_NAME=App2
    volumes:
      - shared_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  app3:
    build: ./backend
    environment:
      - APP_NAME=App3
    volumes:
      - shared_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:latest
    # nginx.conf harus di folder ./nginx/nginx.conf
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro    # nginx config (read-only)
      - ./nginx/ssl:/etc/nginx/ssl:ro                  # sertifikat SSL (read-only)
      - ./frontend:/usr/share/nginx/html:ro            # frontend static files
      - shared_logs:/var/log/nginx                     # shared log volume (nginx + backend)
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy

volumes:
  # Shared volume agar semua log (nginx + backend) terkumpul di satu tempat
  shared_logs:
