version: '3'
services:
  app1:
    build: ./backend
    environment:
      - APP_NAME=App1

  app2:
    build: ./backend
    environment:
      - APP_NAME=App2

  app3:
    build: ./backend
    environment:
      - APP_NAME=App3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
